
export const SCREENS = {
    TAB: "TAB",
    HOME: "HOME",
    CONSULTATION: "CONSULTATION",
    SHOP: "SHOP",
    RECORDS: "RECORDS",

    BOOKING: "BOOKING",
    DOCTOR_DETAILS: "DOCTOR_DETAILS",
    MY_BOOKINGS: "MY_BOOKINGS"
}